[package]
name = "verify-stark"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Lightweight crate to verify a v2 STARK proof"

[dependencies]
openvm-circuit = { workspace = true }
stark-backend-v2 = { workspace = true }
recursion-circuit = { workspace = true }
continuations-v2 = { workspace = true }

eyre = { workspace = true }
p3-field = { workspace = true }
thiserror = { workspace = true }

[features]
default = ["parallel"]
parallel = [
    "stark-backend-v2/parallel",
    "recursion-circuit/parallel",
    "continuations-v2/parallel"
]
